services:
  app:
    image: lwweaponofchoicecr.azurecr.io/filevault-app-clean:latest # <- Built from Dockerfile and pushed to ACR
    container_name: nodejs
    restart: always
    ports:
      - "8080:3000"
    command: npm start
    environment:
      - AZURE_STORAGE_ACCOUNT_NAME={{ azure_storage_account_name }}
      - AZURE_STORAGE_ACCOUNT_KEY={{ azure_storage_account_key }}
      - AZURE_CONTAINER_NAME={{ azure_container_name }}
      - PORT=3000

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3001:3000"
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge