services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/src/azure-sa
    container_name: nodejs
    restart: always
    ports:
      - "3000:3000"
    command: npm start