global:
  scrape_interval: 15s  # Scrape targets every 15 seconds

scrape_configs:
  - job_name: 'filevault-app'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['nodejs:3000']  # Use the Docker service name and port