---
- name: Set up Docker and run filevault container
  hosts: filevault-app-servers
  become: yes

  vars_files:
    - ../vault.yml

  vars:
    acr_login_server: "lwweaponofchoicecr.azurecr.io"
    acr_username: "lwweaponofchoicecr"
    container_name: "filevault-app-clean"
    container_port: 3000
    host_port: 8080

  tasks:
    - name: Ensure Docker is installed
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Ensure pip is installed
      apt:
        name: pip
        state: present
        update_cache: yes

    - name: Install Docker python module
      pip:
        name: docker

    - name: Log into Azure Container Registry
      shell: >
        docker login {{ acr_login_server }}
        -u {{ acr_username }}
        -p {{ acr_password }}
      register: acr_login_result
      changed_when: "'Login Succeeded' not in acr_login_result.stdout"

    - name: Pull the filevault-app image
      docker_image:
        name: "{{ acr_login_server }}/{{ container_name }}"
        tag: "latest"
        source: pull

    - name: Run filevault-app container
      docker_container:
        name: "{{ container_name }}"
        image: "{{ acr_login_server }}/{{ container_name }}:latest"
        state: started
        restart_policy: always
        ports:
          - "{{ host_port }}:{{ container_port }}"